local function header()
	term.setCursorPos(1,1)
	term.setTextColor(colors.yellow)
	print("Version: "..mc.version)
	term.setTextColor(colors.lightGrey)
	term.setCursorPos(1, 3)
	mc.center("MINECRAFT!")
	mc.center("     -In CC!")
	term.setTextColor(colors.white)
	term.setCursorPos(1, 6)
	end
